// Code generated by MockGen. DO NOT EDIT.
// Source: ./types.go
//
// Generated by this command:
//
//	mockgen -source=./types.go -package=executormocks -destination=./mocks/executor.mock.go
//

// Package executormocks is a generated GoMock package.
package executormocks

import (
	context "context"
	reflect "reflect"
	time "time"

	executor "github.com/ecodeclub/ecron/internal/executor"
	task "github.com/ecodeclub/ecron/internal/task"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Explore mocks base method.
func (m *MockExecutor) Explore(ctx context.Context, eid int64, t task.Task) <-chan executor.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Explore", ctx, eid, t)
	ret0, _ := ret[0].(<-chan executor.Result)
	return ret0
}

// Explore indicates an expected call of Explore.
func (mr *MockExecutorMockRecorder) Explore(ctx, eid, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Explore", reflect.TypeOf((*MockExecutor)(nil).Explore), ctx, eid, t)
}

// Name mocks base method.
func (m *MockExecutor) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExecutorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExecutor)(nil).Name))
}

// Run mocks base method.
func (m *MockExecutor) Run(ctx context.Context, t task.Task, eid int64) (task.ExecStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, t, eid)
	ret0, _ := ret[0].(task.ExecStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockExecutorMockRecorder) Run(ctx, t, eid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockExecutor)(nil).Run), ctx, t, eid)
}

// Stop mocks base method.
func (m *MockExecutor) Stop(ctx context.Context, t task.Task, eid int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx, t, eid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockExecutorMockRecorder) Stop(ctx, t, eid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockExecutor)(nil).Stop), ctx, t, eid)
}

// TaskTimeout mocks base method.
func (m *MockExecutor) TaskTimeout(t task.Task) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TaskTimeout", t)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// TaskTimeout indicates an expected call of TaskTimeout.
func (mr *MockExecutorMockRecorder) TaskTimeout(t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TaskTimeout", reflect.TypeOf((*MockExecutor)(nil).TaskTimeout), t)
}
